### ISSUE TITLE
Script only syncs ratings from parts of my library

### ISSUE THREAD

**Issue by Paraxes** [wylek/plex-music-import-ratings#16]
Hello,
first of all, thank you for the script.

I have a problem however.

Whenever I run the script, it recognizes the roughly 3,5k songs with ratings from my iTunes library and connects to Plex without issues. However, it only syncs the ratings of roughly 1000 of the 3,5k songs it originally recognized.

I tried the sync of the itunes library.xml  with the original file paths of windows (E:\Itunes ....) where my music library is on my windows PC and also tried to change the file paths of the itunes library.xml to the paths of my music library on my Synology NAS (/volume1/multimedia ...) where my plex music library resides - same result.

Is it simply not fully compatible with iTunes for Windows? Does it need Apple Music? Or has it something to do with the old version of iTunes I am using (12.7.2.58).

Thank you.

**Comment by wylek** [comment]
Hello @Paraxes, unfortunately I do not have the ability to test the script with iTunes for Windows... but it "should" work the same as with macOS. Apple Music (assuming you mean subscription) is not required.

Do you have a details.log file in the script folder after running it? That may help you analyze which tracks are being updated in your Plex library.

**Comment by Paraxes** [comment]
Thank you for the quick answer. Yes, I have a log file and at first I thought it had something to do with my library containing a lot of Japanese and Korean bands written in their native language but that wasn't it since a lot of them get synced. 

There really isn't any kind of pattern to what it syncs or not; it feels completely arbitrary sadly.

But since you don't have Windows I assume it has something to do with being iTunes and/or my older version of iTunes, which is a shame since I was so incredibly excited finding your script, since it's the only working one for ratings :(

Oh well, not much I can do. Thank you.
