### ISSUE TITLE
libpytunes not on PyPi and submodule not linked

### ISSUE THREAD

**Issue by maximecharriere** [wylek/plex-music-import-ratings#4]
Hey
In you instruction you suggested to do `pip install libpytunes` but libpytunes isn't on PyPi.
It also looks like you've linked a submodule to libpytunes, but the link doesn't seem to work:  
`fatal: No url found for submodule path 'libpytunes' in .gitmodules`.

I think you're referring to this project? https://github.com/liamks/libpytunes

**Comment by wylek** [comment]
Hi @maximecharriere, yes.. that's the correct project dependency. I've updated the readme and added a pyproject.toml configuration file to help.
